# https://github.com/golangci/awesome-go-linters
run:
  skip-files:
    - "/zz_generated_"
  skip-dirs:
    - "generated"
    - "pkg"
  tests: true
  build-tags:
    - test
linters:
  enable:
    # 风险
    - vet
    - staticcheck
    - bodyclose
    - errcheck
    # 整洁
    - gofmt
    - goimports
    - whitespace
    - deadcode
    - unused
    - unparam
    - ineffassign
    - scopelint
    - godox
    # 性能
    - maligned
    - prealloc
    # 未知
    - gocognit
    - gocritic
    # 风格
    - stylecheck
    - golint
#    - funlen
    - lll
    #  清晰
#    - dupl
    - goconst
      # - gomnd
    - gosimple
    - gochecknoinits
    # 安全
#    - gosec
  disable:
  #    - gochecknoglobals
  #    - misspell
  #    - gosec
  #    - wsl

  enable-all: false
  disable-all: true
  fast: false
linters-settings:
  maligned:
    suggest-new: true
