#!/usr/bin/env bash
[[ -n $DEBUG ]] && set -x
set -eou pipefail

useage() {
    cat <<HELP
USAGE:
    test-installer SSHCONFIG DASHBOARD
HELP
}

exit_err() {
    echo >&2 "${1}"
    exit 1
}

if [ $# -lt 2 ]; then
    useage
    exit 1
fi

SSHCONFIG=$1
DASHBOARD=$2
NAME=$(mktemp -u -p /home/rancher)
TARGET=/opt/start_harvester_console.sh

CGO_ENABLED=0 GOOS=linux go build
ssh-copy-id "${SSHCONFIG}"
scp harvester-installer "${SSHCONFIG}":"${NAME}"
ssh "${SSHCONFIG}" sudo sed -i "5s:^.*$:${NAME}:" "${TARGET}"
ssh "${SSHCONFIG}" sudo sed -i "s/HARVESTER_DASHBOARD=.*$/HARVESTER_DASHBOARD=$DASHBOARD/" "${TARGET}"
ssh "${SSHCONFIG}" "sudo kill -9 \$(ps aux | grep start_harvester_console | grep -v grep | awk '{print \$2}')"

