#!/usr/bin/env bash
[[ -n $DEBUG ]] && set -x
set -eou pipefail

useage() {
    cat <<HELP
USAGE:
    test-installer SSHCONFIG DASHBOARD
HELP
}

exit_err() {
    echo >&2 "${1}"
    exit 1
}

if [ $# -lt 2 ]; then
    useage
    exit 1
fi

SSHCONFIG=$1
DASHBOARD=$2

mode_file=/opt/harvester-mode
start_script_dir=/usr/bin
remote_temp_dir=/home/rancher
local_temp_dir=/tmp
start_script_name=start-harvester-console.sh
replace_script_name=replace-harvester-console.sh

start_script="${start_script_dir}/${start_script_name}"
start_script_temp="${remote_temp_dir}/${start_script_name}"
local_script_temp="${local_temp_dir}/${replace_script_name}"
bin_name=harvester-installer
bin_name_temp=$(mktemp -u -p "${remote_temp_dir}" -t XXXXX.harvester-console)

CGO_ENABLED=0 GOOS=linux go build

ssh-copy-id "${SSHCONFIG}"

scp "${bin_name}" "${SSHCONFIG}":"${bin_name_temp}"

cat >"${local_script_temp}" << EEOOFF
sudo sed -i "s/HARVESTER_DASHBOARD=.*$/HARVESTER_DASHBOARD=$DASHBOARD/" "${mode_file}"
sudo sed "s:^.*harvester-console$:${bin_name_temp}:" ${start_script} > "${start_script_temp}"
sudo kill -9 \$(ps aux | grep start-harvester-console | grep -v grep | awk '{print \$2}')
EEOOFF

scp "${local_script_temp}" "${SSHCONFIG}":${local_script_temp}
ssh "${SSHCONFIG}" sudo bash -x ${local_script_temp}