#!/usr/bin/env bash
[[ -n $DEBUG ]] && set -x
set -eou pipefail

useage() {
    cat <<HELP
USAGE:
    test-installer SSHCONFIG NAME
HELP
}

exit_err() {
    echo >&2 "${1}"
    exit 1
}

if [ $# -lt 2 ]; then
    useage
    exit 1
fi

SSHCONFIG=$1
NAME=$2

CGO_ENABLED=0 GOOS=linux go build

ssh-copy-id $SSHCONFIG
scp harvester-installer $SSHCONFIG:/home/rancher/$NAME
ssh $SSHCONFIG sudo sed -i "5s:^.*$:/home/rancher/$NAME:" /opt/start_harvester_console.sh
ssh $SSHCONFIG sudo cat /opt/start_harvester_console.sh
ssh $SSHCONFIG "sudo kill -9 \$(ps aux | grep start_harvester_console | grep -v grep | awk '{print \$2}')"

