---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: harvester-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: harvester
          servicePort: 8443
    host: harvester.ingress.example.com
