---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: harvester-ingress
  namespace: harvester-system
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
  - secretName: harvester-tls-cert
  rules:
  - host: harvester.ingress.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: harvester
          servicePort: 8080
