apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-vlan1
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "bridge1",
    "type": "bridge",
    "bridge": "harvester-br0",
    "vlan": 110,
    "ipam": { "type": "static" }
  }'
