apiVersion: v1
kind: Pod
metadata:
  name: pod-vlan-m1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{
      "name": "bridge-vlan1",
      "ips": ["10.10.1.10/24"]
    }]'
spec:
  # nodeSelector:
  #   mynode: m1
  containers:
  - name: samplepod
    imagePullPolicy: IfNotPresent
    command: ["sleep", "99999"]
    image: busybox
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-vlan-w1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{
      "name": "bridge-vlan1",
      "ips": ["10.10.1.11/24"]
    }]'
spec:
  # nodeSelector:
  #   mynode: w1
  containers:
  - name: samplepod
    imagePullPolicy: IfNotPresent
    command: ["sleep", "99999"]
    image: busybox
